/*
 * Données entièrement fictives pour la démonstration J-14 → J-0.
 * Le rendu et la logique d'interface se trouvent dans app.js.
 */
window.SIMULATION_DATA = {
  title: "Installation simulée d'une ligne de conditionnement",
  disclaimer: "Scénario fictif — aucune référence client réelle.",
  days: [
    { day: -14, label: "Cadrage initial" },
    { day: -13, label: "Premières demandes" },
    { day: -12, label: "Absence de réponse" },
    { day: -11, label: "Réceptions partielles" },
    { day: -10, label: "Complément obtenu" },
    { day: -9, label: "Information contradictoire" },
    { day: -8, label: "Retard annoncé" },
    { day: -7, label: "Instruction client" },
    { day: -6, label: "Backup et nouveau point" },
    { day: -5, label: "Disponibilité modifiée" },
    { day: -4, label: "Solutions en cours" },
    { day: -3, label: "Document incomplet" },
    { day: -2, label: "Vue finale" },
    { day: -1, label: "Dernières confirmations" },
    { day: 0, label: "Intervention planifiée" }
  ],
  statusMeta: {
    launch: { label: "À lancer", className: "status-launch" },
    progress: { label: "En cours", className: "status-progress" },
    followup: { label: "À relancer", className: "status-followup" },
    received: { label: "Reçu à contrôler", className: "status-received" },
    incomplete: { label: "Reçu incomplet", className: "status-incomplete" },
    contradictory: { label: "Information contradictoire", className: "status-contradictory" },
    blocked: { label: "Bloqué", className: "status-blocked" },
    decision: { label: "Décision nécessaire", className: "status-decision" },
    closed: { label: "Fermé selon critère client", className: "status-closed" }
  },
  prerequisites: [
    {
      id: "PR-01",
      title: "Accès site des intervenants",
      responsible: "Référente accès site",
      company: "Site client simulé",
      primary: "Contact principal accès",
      backup: "Responsable sûreté adjoint",
      channel: "E-mail",
      due: "J-3",
      proof: "Confirmation nominative des accès autorisés",
      criticality: "Haute",
      escalation: "Backup après une relance sans réponse ; client si accès non confirmé à J-3",
      impact: "Entrée sur site potentiellement retardée",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Liste des intervenants attendue avant lancement des badges.", source: "Cadrage client", action: "Demande initiale préparée", nextAction: "Envoyer la liste nominative", nextDate: "J-11" },
        { day: -11, status: "progress", info: "Liste transmise au service accès.", source: "Intégrateur simulé", action: "Transmission au contact accès", nextAction: "Obtenir la confirmation des badges", nextDate: "J-7" },
        { day: -6, status: "followup", info: "Contact principal absent ; message d'absence reçu.", source: "Réponse automatique simulée", action: "Backup identifié et contacté", nextAction: "Obtenir la confirmation du backup", nextDate: "J-5" },
        { day: -4, status: "received", info: "Confirmation nominative reçue du backup.", source: "Responsable sûreté adjoint", action: "Rapprochement avec la liste attendue", nextAction: "Contrôler selon le critère client", nextDate: "J-3" },
        { day: -2, status: "closed", info: "Tous les noms transmis figurent dans la confirmation reçue.", source: "Confirmation accès simulée", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-02",
      title: "Liste définitive des techniciens",
      responsible: "Chef de projet intégrateur",
      company: "Intégrateur simulé",
      primary: "Coordinateur installation",
      backup: "Responsable service terrain",
      channel: "E-mail",
      due: "J-11",
      proof: "Liste nominative complète selon le modèle client",
      criticality: "Haute",
      escalation: "Responsable service terrain si aucune réponse après relance",
      impact: "Accès et hébergement impossibles à finaliser",
      activeFrom: -14,
      changes: [
        { day: -14, status: "launch", info: "Responsable et preuve attendue définis.", source: "Cadrage client", action: "Point créé", nextAction: "Demander la liste définitive", nextDate: "J-13" },
        { day: -13, status: "progress", info: "Demande envoyée au coordinateur installation.", source: "E-mail de poursuite simulé", action: "Demande initiale envoyée", nextAction: "Contrôler la réponse", nextDate: "J-12" },
        { day: -12, status: "followup", info: "Aucune réponse à la demande initiale.", source: "Journal de suivi simulé", action: "Relance intégrateur", nextAction: "Escalader au backup sans réponse", nextDate: "J-11" },
        { day: -11, status: "closed", info: "Liste reçue et complète selon le critère défini.", source: "Intégrateur simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-03",
      title: "Documents sécurité demandés",
      responsible: "Coordinateur HSE",
      company: "Intégrateur simulé",
      primary: "Coordinateur HSE",
      backup: "Chef de projet intégrateur",
      channel: "E-mail",
      due: "J-2",
      proof: "Dossier contenant toutes les pièces listées par le client",
      criticality: "Haute",
      escalation: "Client si le dossier reste incomplet à l'échéance",
      impact: "Instruction sécurité ou accès susceptibles d'être retardés",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Liste des pièces attendues transmise au responsable.", source: "Cadrage client", action: "Demande initiale envoyée", nextAction: "Recevoir le dossier", nextDate: "J-4" },
        { day: -4, status: "received", info: "Dossier reçu, contrôle de complétude en cours.", source: "Coordinateur HSE simulé", action: "Réception tracée", nextAction: "Comparer à la liste client", nextDate: "J-3" },
        { day: -3, status: "incomplete", info: "Une pièce demandée dans la liste client est absente.", source: "Contrôle documentaire simulé", action: "Complément ciblé demandé", nextAction: "Recevoir la pièce manquante", nextDate: "J-2" },
        { day: -2, status: "received", info: "Pièce manquante reçue dans le délai.", source: "Coordinateur HSE simulé", action: "Complément réceptionné", nextAction: "Contrôle final selon la liste", nextDate: "J-1" },
        { day: -1, status: "closed", info: "Toutes les pièces listées par le client sont présentes.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-04",
      title: "Zone d'installation libérée",
      responsible: "Responsable production",
      company: "Site client simulé",
      primary: "Superviseur de zone",
      backup: "Responsable production",
      channel: "E-mail + photos",
      due: "J-9",
      proof: "Photos des quatre angles définis par le client",
      criticality: "Haute",
      escalation: "Responsable production si les quatre vues ne sont pas obtenues",
      impact: "Démarrage du montage potentiellement retardé",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Quatre vues de la zone sont attendues.", source: "Cadrage client", action: "Demande initiale envoyée", nextAction: "Recevoir les quatre photos", nextDate: "J-11" },
        { day: -11, status: "incomplete", info: "Deux photos reçues sur les quatre attendues.", source: "Superviseur de zone simulé", action: "Complément ciblé demandé", nextAction: "Recevoir les deux vues manquantes", nextDate: "J-10" },
        { day: -10, status: "closed", info: "Les quatre vues prévues par le critère client sont présentes.", source: "Superviseur de zone simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-05",
      title: "Travaux de préparation du sol terminés",
      responsible: "Conducteur de travaux",
      company: "Sous-traitant sol simulé",
      primary: "Conducteur de travaux",
      backup: "Responsable d'agence",
      channel: "Téléphone + e-mail",
      due: "J-7",
      proof: "Confirmation et photos définies par le client",
      criticality: "Critique",
      escalation: "Décision client dès qu'un décalage est annoncé",
      impact: "Décalage potentiel du démarrage et de la mobilisation",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Fin des travaux annoncée pour J-8.", source: "Planning sous-traitant simulé", action: "Échéance et preuve tracées", nextAction: "Reconfirmer l'avancement", nextDate: "J-10" },
        { day: -10, status: "progress", info: "Travaux annoncés en cours conformément au dernier échange.", source: "Conducteur de travaux simulé", action: "Avancement reconfirmé", nextAction: "Obtenir la confirmation de fin", nextDate: "J-8" },
        { day: -8, status: "decision", info: "Le sous-traitant annonce une fin un jour plus tard que prévu.", source: "Appel sous-traitant simulé", action: "Blocage documenté et chef de projet sollicité", nextAction: "Recevoir l'instruction du client", nextDate: "J-7", attention: true },
        { day: -7, status: "progress", info: "Nouvelle instruction et nouvelle échéance confirmées par le client.", source: "Décision chef de projet simulée", action: "Poursuite reprise selon l'instruction", nextAction: "Obtenir preuve de fin des travaux", nextDate: "J-2" },
        { day: -2, status: "received", info: "Photos et confirmation de fin reçues.", source: "Sous-traitant sol simulé", action: "Éléments reçus", nextAction: "Contrôler selon le critère client", nextDate: "J-1" },
        { day: -1, status: "closed", info: "Le jeu de preuves attendu est complet selon le critère client.", source: "Journal de suivi simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-06",
      title: "Alimentation électrique disponible",
      responsible: "Responsable maintenance",
      company: "Site client simulé",
      primary: "Responsable maintenance",
      backup: "Technicien utilités",
      channel: "E-mail",
      due: "J-2",
      proof: "Confirmation écrite selon les critères définis par le client",
      criticality: "Critique",
      escalation: "Client si la confirmation n'est pas renouvelée à J-4",
      impact: "Essais électriques potentiellement impossibles",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Dernière information : raccordement prévu pour cette semaine.", source: "Compte rendu initial simulé", action: "Information initiale tracée", nextAction: "Demander une confirmation renouvelée", nextDate: "J-6" },
        { day: -6, status: "followup", info: "La confirmation initiale n'a pas encore été renouvelée.", source: "Journal de suivi simulé", action: "Relance de reconfirmation", nextAction: "Obtenir la confirmation écrite", nextDate: "J-4" },
        { day: -4, status: "received", info: "Confirmation écrite reçue du responsable désigné.", source: "Responsable maintenance simulé", action: "Réception tracée", nextAction: "Comparer au critère client", nextDate: "J-3" },
        { day: -2, status: "closed", info: "La confirmation reçue satisfait le critère défini.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-07",
      title: "Utilités nécessaires disponibles",
      responsible: "Technicien utilités",
      company: "Site client simulé",
      primary: "Technicien utilités",
      backup: "Responsable maintenance",
      channel: "E-mail",
      due: "J-3",
      proof: "Confirmation des utilités listées par le client",
      criticality: "Haute",
      escalation: "Responsable maintenance si une utilité reste non confirmée",
      impact: "Essais fonctionnels potentiellement limités",
      activeFrom: -14,
      changes: [
        { day: -14, status: "launch", info: "Liste des utilités et critères fournie par le client.", source: "Cadrage client", action: "Point créé", nextAction: "Envoyer la demande", nextDate: "J-12" },
        { day: -12, status: "progress", info: "Demande envoyée au technicien utilités.", source: "E-mail de poursuite simulé", action: "Demande initiale envoyée", nextAction: "Recevoir la confirmation détaillée", nextDate: "J-6" },
        { day: -6, status: "received", info: "Tableau de disponibilité reçu.", source: "Technicien utilités simulé", action: "Réception tracée", nextAction: "Comparer à la liste attendue", nextDate: "J-5" },
        { day: -4, status: "closed", info: "Toutes les utilités listées sont confirmées.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-08",
      title: "Moyen de déchargement réservé",
      responsible: "Coordinateur logistique",
      company: "Site client simulé",
      primary: "Coordinateur logistique",
      backup: "Responsable magasin",
      channel: "Téléphone + e-mail",
      due: "J-2",
      proof: "Réservation identifiée sur le créneau prévu",
      criticality: "Critique",
      escalation: "Décision client si le moyen annoncé devient indisponible",
      impact: "Location alternative, attente transporteur et replanification potentielles",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Moyen annoncé comme normalement disponible.", source: "Compte rendu initial simulé", action: "Information initiale tracée", nextAction: "Obtenir une réservation ferme", nextDate: "J-7" },
        { day: -7, status: "progress", info: "Disponibilité encore annoncée, référence de réservation attendue.", source: "Coordinateur logistique simulé", action: "Confirmation demandée", nextAction: "Recevoir la référence de réservation", nextDate: "J-5" },
        { day: -5, status: "decision", info: "Le moyen supposé disponible ne l'est finalement plus.", source: "Coordinateur logistique simulé", action: "Exception et impact potentiel signalés", nextAction: "Obtenir la décision du client", nextDate: "J-4", attention: true },
        { day: -4, status: "progress", info: "Le client demande la poursuite d'une solution alternative définie.", source: "Instruction client simulée", action: "Demande de réservation alternative envoyée", nextAction: "Recevoir la confirmation de réservation", nextDate: "J-3" },
        { day: -3, status: "received", info: "Réservation alternative reçue sur le créneau prévu.", source: "Loueur manutention simulé", action: "Référence reçue", nextAction: "Contrôler le créneau", nextDate: "J-2" },
        { day: -2, status: "closed", info: "La réservation correspond au créneau défini par le client.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-09",
      title: "Créneau de livraison confirmé",
      responsible: "Planificateur transport",
      company: "Transporteur simulé",
      primary: "Planificateur transport",
      backup: "Responsable exploitation",
      channel: "E-mail",
      due: "J-7",
      proof: "Horaire commun confirmé par le transporteur et le site",
      criticality: "Haute",
      escalation: "Client si les deux parties ne convergent pas avant J-7",
      impact: "Attente camion et décalage du déchargement potentiels",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Confirmation commune du site et du transporteur attendue.", source: "Cadrage client", action: "Demandes envoyées aux deux parties", nextAction: "Comparer les réponses", nextDate: "J-9" },
        { day: -9, status: "contradictory", info: "Le site et le transporteur indiquent deux horaires différents.", source: "Deux e-mails simulés", action: "Confirmation commune demandée", nextAction: "Obtenir un horaire partagé", nextDate: "J-8" },
        { day: -8, status: "received", info: "Les deux interlocuteurs répondent sur un horaire commun.", source: "Fil d'e-mail commun simulé", action: "Confirmation commune reçue", nextAction: "Contrôler selon le critère", nextDate: "J-7" },
        { day: -7, status: "closed", info: "L'horaire commun satisfait le critère client.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-10",
      title: "Plan d'implantation final reçu",
      responsible: "Bureau d'études",
      company: "Intégrateur simulé",
      primary: "Projeteur référent",
      backup: "Responsable bureau d'études",
      channel: "E-mail",
      due: "J-6",
      proof: "Version identifiée comme finale par le responsable désigné",
      criticality: "Haute",
      escalation: "Responsable bureau d'études en l'absence de réponse à J-7",
      impact: "Préparation et repérage potentiellement retardés",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Version finale demandée au bureau d'études.", source: "Cadrage client", action: "Demande initiale envoyée", nextAction: "Recevoir la version finale", nextDate: "J-8" },
        { day: -7, status: "followup", info: "Aucune version finale reçue à la date de contrôle.", source: "Journal de suivi simulé", action: "Backup du bureau d'études contacté", nextAction: "Obtenir la version identifiée", nextDate: "J-6" },
        { day: -6, status: "closed", info: "Version reçue et identifiée comme finale par le responsable désigné.", source: "Responsable bureau d'études simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-11",
      title: "Responsable client disponible pour essais / SAT",
      responsible: "Responsable industrialisation",
      company: "Site client simulé",
      primary: "Responsable industrialisation",
      backup: "Responsable production",
      channel: "E-mail",
      due: "J-4",
      proof: "Nom et plage de disponibilité confirmés",
      criticality: "Haute",
      escalation: "Client si aucune couverture n'est confirmée à J-4",
      impact: "Essais ou arbitrages potentiellement retardés",
      activeFrom: -14,
      changes: [
        { day: -14, status: "progress", info: "Présence annoncée lors du cadrage initial.", source: "Compte rendu initial simulé", action: "Information initiale tracée", nextAction: "Reconfirmer la disponibilité", nextDate: "J-8" },
        { day: -8, status: "followup", info: "Le responsable annonce un changement de disponibilité.", source: "Responsable industrialisation simulé", action: "Couverture de remplacement demandée", nextAction: "Obtenir le nom du remplaçant", nextDate: "J-7" },
        { day: -7, status: "received", info: "Un responsable de remplacement et sa plage sont confirmés.", source: "Site client simulé", action: "Confirmation reçue", nextAction: "Contrôler la couverture attendue", nextDate: "J-6" },
        { day: -6, status: "closed", info: "La plage de couverture satisfait le critère client.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-12",
      title: "Matières / consommables pour essais disponibles",
      responsible: "Responsable production",
      company: "Site client simulé",
      primary: "Planificateur production",
      backup: "Responsable production",
      channel: "E-mail",
      due: "J-1",
      proof: "Quantités prévues confirmées selon la liste client",
      criticality: "Haute",
      escalation: "Responsable production si une quantité reste ouverte à J-2",
      impact: "Essais en charge potentiellement limités",
      activeFrom: -14,
      changes: [
        { day: -14, status: "launch", info: "Échéance plus tardive ; point planifié dès le cadrage.", source: "Cadrage client", action: "Prochaine action planifiée", nextAction: "Demander l'état des quantités", nextDate: "J-4" },
        { day: -4, status: "progress", info: "État des quantités demandé au planificateur production.", source: "E-mail de poursuite simulé", action: "Demande envoyée", nextAction: "Recevoir la confirmation", nextDate: "J-2" },
        { day: -2, status: "received", info: "Quantités annoncées disponibles ; contrôle en cours.", source: "Planificateur production simulé", action: "Confirmation reçue", nextAction: "Comparer à la liste client", nextDate: "J-1" },
        { day: -1, status: "closed", info: "Les quantités confirmées correspondent à la liste client.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    },
    {
      id: "PR-13",
      title: "Évacuation des emballages confirmée",
      responsible: "Responsable magasin",
      company: "Site client simulé",
      primary: "Responsable magasin",
      backup: "Coordinateur logistique",
      channel: "E-mail",
      due: "J-2",
      proof: "Zone et responsable d'évacuation confirmés",
      criticality: "Modérée",
      escalation: "Coordinateur logistique si le point reste ouvert à J-2",
      impact: "Encombrement temporaire de la zone de montage",
      activeFrom: -6,
      isAdded: true,
      changes: [
        { day: -6, status: "progress", info: "Nouveau prérequis ajouté par le client en cours d'opération.", source: "Instruction client simulée", action: "Responsable, échéance et preuve enregistrés", nextAction: "Demander la confirmation", nextDate: "J-4" },
        { day: -4, status: "followup", info: "Aucune réponse à la demande initiale.", source: "Journal de suivi simulé", action: "Relance responsable magasin", nextAction: "Obtenir la zone et le responsable", nextDate: "J-3" },
        { day: -3, status: "received", info: "Zone et responsable communiqués.", source: "Responsable magasin simulé", action: "Confirmation reçue", nextAction: "Comparer au critère client", nextDate: "J-2" },
        { day: -2, status: "closed", info: "Les deux éléments attendus sont confirmés.", source: "Journal de contrôle simulé", action: "Critère client satisfait", nextAction: "Aucune — point fermé", nextDate: "—" }
      ]
    }
  ],
  activities: [
    { day: -14, title: "12 points structurés", detail: "Responsables, échéances, preuves et règles d'escalade enregistrés." },
    { day: -13, title: "Premières demandes envoyées", detail: "Chaque message précise l'opération, l'élément et la date attendue." },
    { day: -12, title: "Relance intégrateur", detail: "Aucune réponse pour la liste définitive des techniciens." },
    { day: -11, title: "Liste techniciens fermée", detail: "La liste reçue satisfait le critère défini par le client." },
    { day: -11, title: "Photos incomplètes", detail: "Deux vues manquent ; un complément ciblé est demandé." },
    { day: -10, title: "Complément reçu", detail: "Les quatre vues attendues sont maintenant présentes." },
    { day: -9, title: "Deux horaires différents", detail: "Le site et le transporteur sont invités à confirmer un horaire commun." },
    { day: -8, title: "Retard sous-traitant annoncé", detail: "Le décalage touche une échéance critique ; décision client requise.", attention: true },
    { day: -8, title: "Disponibilité SAT modifiée", detail: "Une couverture de remplacement est demandée au site." },
    { day: -7, title: "Instruction client reçue", detail: "La poursuite reprend selon la nouvelle échéance de travaux." },
    { day: -7, title: "Créneau commun confirmé", detail: "Le site et le transporteur convergent sur le même horaire." },
    { day: -6, title: "Backup utilisé", detail: "Le contact accès principal est absent ; son remplaçant est contacté." },
    { day: -6, title: "Nouveau prérequis ajouté", detail: "Évacuation des emballages : responsable, preuve et échéance définis par le client." },
    { day: -5, title: "Moyen de déchargement indisponible", detail: "L'impact potentiel est rendu visible avant mobilisation ; décision client requise.", attention: true },
    { day: -4, title: "Solution alternative poursuivie", detail: "La demande de réservation suit l'instruction donnée par le client." },
    { day: -4, title: "Accès reçu via le backup", detail: "La confirmation nominative peut être contrôlée." },
    { day: -3, title: "Dossier sécurité incomplet", detail: "Une pièce manque ; le complément est demandé sans solliciter le chef de projet." },
    { day: -3, title: "Réservation alternative reçue", detail: "La référence et le créneau sont contrôlés." },
    { day: -2, title: "Majorité des points fermés", detail: "Les derniers éléments restent dans leur délai ; aucune surprise critique inconnue." },
    { day: -2, title: "Nouveau prérequis fermé", detail: "La zone et le responsable d'évacuation sont confirmés." },
    { day: -1, title: "Derniers contrôles terminés", detail: "Les critères documentaires restants sont satisfaits." },
    { day: 0, title: "Intervention planifiée", detail: "Le service n'autorise pas la mobilisation ; la décision reste au client." }
  ]
};
