from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("connexion/", views.login_view, name="login"),
    path("connexion/mfa/configurer/", views.mfa_setup, name="mfa_setup"),
    path("connexion/mfa/secours/", views.mfa_recovery_codes, name="mfa_recovery_codes"),
    path("connexion/mfa/verifier/", views.mfa_verify, name="mfa_verify"),
    path("deconnexion/", views.logout_view, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("missions/", views.mission_list, name="mission_list"),
    path("missions/nouvelle/", views.mission_create, name="mission_create"),
    path("missions/<uuid:mission_id>/", views.mission_detail, name="mission_detail"),
    path("missions/<uuid:mission_id>/qualification/", views.mission_qualification, name="mission_qualification"),
    path("missions/<uuid:mission_id>/acceptation/", views.mission_acceptance, name="mission_acceptance"),
    path("missions/<uuid:mission_id>/faisabilite/", views.mission_feasibility, name="mission_feasibility"),
    path("missions/<uuid:mission_id>/finance/", views.mission_financial, name="mission_financial"),
    path("missions/<uuid:mission_id>/etat/", views.mission_transition, name="mission_transition"),
    path("missions/<uuid:mission_id>/cloture/", views.mission_close, name="mission_close"),
    path("missions/<uuid:mission_id>/t0/", views.mission_capture_t0, name="mission_capture_t0"),
    path("missions/<uuid:mission_id>/contacts/nouveau/", views.contact_create, name="contact_create"),
    path("missions/<uuid:mission_id>/prerequis/nouveau/", views.prerequisite_create, name="prerequisite_create"),
    path("missions/<uuid:mission_id>/documents/nouveau/", views.document_upload, name="document_upload"),
    path("missions/<uuid:mission_id>/publier/", views.mission_publish, name="mission_publish"),
    path("missions/<uuid:mission_id>/extension/", views.extension_create, name="extension_create"),
    path("missions/<uuid:mission_id>/export/", views.mission_export, name="mission_export"),
    path("prerequis/<uuid:prerequisite_id>/", views.prerequisite_detail, name="prerequisite_detail"),
    path("prerequis/<uuid:prerequisite_id>/modifier/", views.prerequisite_update, name="prerequisite_update"),
    path("prerequis/<uuid:prerequisite_id>/action/", views.prerequisite_action, name="prerequisite_action"),
    path("prerequis/<uuid:prerequisite_id>/escalade/", views.prerequisite_escalate, name="prerequisite_escalate"),
    path("documents/<uuid:document_id>/telecharger/", views.document_download, name="document_download"),
    path("documents/<uuid:document_id>/partage/", views.document_toggle_share, name="document_toggle_share"),
    path("publications/<uuid:publication_id>/revoquer/", views.publication_revoke, name="publication_revoke"),
    path("portail/", views.portal_home, name="portal_home"),
    path("portail/publications/<uuid:publication_id>/", views.portal_publication, name="portal_publication"),
    path("api/v1/missions/<uuid:mission_id>/synthese/", views.portal_api_summary, name="portal_api_summary"),
    path("clients/", views.organization_list, name="organization_list"),
    path("clients/nouveau/", views.organization_create, name="organization_create"),
    path("clients/viewers/nouveau/", views.viewer_create, name="viewer_create"),
    path("clients/<uuid:tenant_id>/acces/", views.mission_access_create, name="mission_access_create"),
    path("parametres/", views.config_view, name="config"),
    path("incidents/", views.incident_list, name="incident_list"),
    path("incidents/nouveau/", views.incident_create, name="incident_create"),
    path("securite/revoquer-sessions/", views.revoke_other_sessions, name="revoke_other_sessions"),
]
