# Generated by Django 5.2.17 on 2026-08-20 20:18

from django.db import migrations, models

import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_postgres_rls_and_immutability'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='retention_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='retention_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=operations.models.document_upload_path),
        ),
    ]
